### PR TITLE
AT-62-challenge-dashboard-query

### PR DESCRIPTION
**Pull request by b7rch4**
Jira: https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-62

Problem: We needed to create an array of JS objects, each containing completion data for each module challenge, in order to be able to display it on the frontend.

Solution: We have created a function which will query the database, and construct the desired response from the module challenge data.

### CODE REVIEW

**Comment by b7rch4** [comment]
> Good, but what am I missing - where are the cypress tests for the request/response assertion?

Currently these changes are just sub-components of the response, we next need to create a Dashboard class which will call the functions we've made in AT-62, AT-65 and AT-52.
That class will then combine the returned arrays from the three functions and build the final JS object.
The router will call a method from this class so it can pass the reponse to the frontend, and when we do this we'll set up the Cypress tests to ensure the final response is as expected.

Hope this makes sense!

I think we've ended up building inside out instead of beginning with our feature tests - mainly because we wanted to try and make a series of smaller commits/merges instead of one big one :)

**Comment by dearshrewdwit** [comment]
Ok - thanks for the explanation. Add it to the PR description next time for context

**Review by dearshrewdwit — CHANGES_REQUESTED** [review]
Rename the spec file name to match `challengeRatio`

**Comment by FractalFraction** [comment]
Have made changes requested (apart from Cypress tests - as explained above).

**Review by dearshrewdwit — APPROVED** [review]

**Review by Reginmaru — APPROVED** [review]

**Pull request merged**
