### PR TITLE
database for Self-Assessments 

### PR DESCRIPTION
**Pull request by Neokrieger**
Update adds a database model for Self Assessments
https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?issueParent=10138&selectedIssue=AT-12

### CODE REVIEW

**Review by grantwhiteman — DISMISSED** [review]
LGTM

**Review by dearshrewdwit — CHANGES_REQUESTED** [review]
Good. Thanks for keeping it small.

Can you:
1. Add the Jira Issue link in the PR
2. Add a brief description of the proposed change
3. Change model name - Model names should be capitalised camelCase
4. Force squash the commits 'Database' that show unnecessary adding/removing of config

**Comment by Neokrieger** [comment]
> Good. Thanks for keeping it small.
> 
> Can you:
> 
> 1. Add the Jira Issue link in the PR
> 2. Add a brief description of the proposed change
> 3. Change model name - Model names should be capitalised camelCase
> 4. Force squash the commits 'Database' that show unnecessary adding/removing of config

Did i do it correctly?

**Review by dearshrewdwit — DISMISSED** [review]

**Review by grantwhiteman — APPROVED** [review]
LGTM

**Review by grantwhiteman — APPROVED** [review]
LGTM

**Review by dearshrewdwit — APPROVED** [review]

**Pull request merged**
