### PR TITLE
AT-10 done - added tables

### PR DESCRIPTION
**Pull request by benclayton98**

### CODE REVIEW

**Review by OllieVanD — APPROVED** [review]
All looks good.

**Review by dearshrewdwit — CHANGES_REQUESTED** [review]
Good. Thanks for keeping it small.

Can you:
- Add the Jira Issue link in the PR
- Add a brief description of the proposed change
- Change table name - table names are capitalised camelCase
- Change model file-name - model file names are lowercase camelCase

**Comment by benclayton98** [comment]
https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-10

I have added a migrations file and a model file for the creation of a ModuleChallenges table.
Edits since the last push have been to ensure that the casing is correct.
Due to a misunderstanding I merged my two commits, but that single commit is now updated to reflect the changes requested.

**Review by dearshrewdwit — APPROVED** [review]

**Review by OllieVanD — APPROVED** [review]
LGTM

**Pull request merged**
