### PR TITLE
updated cypress dependency to 8.3.0

### PR DESCRIPTION
**Pull request by breeshidy**
Cypress requested an update to improve performance

### CODE REVIEW

**Review by dearshrewdwit — APPROVED** [review]

**Comment by dearshrewdwit** [comment]
@breeshidy In general - try to give a reason why the dependency upgrade is needed in the PR description

**Comment by breeshidy** [comment]
> @breeshidy In general - try to give a reason why the dependency upgrade is needed in the PR description

Done

**Comment by dearshrewdwit** [comment]
@breeshidy let's get this merged. You need 1 more review

**Review by Reginmaru — APPROVED** [review]

**Comment by dearshrewdwit** [comment]
@breeshidy What's this waiting on?

**Pull request merged**
